### ISSUE TITLE
Crash on Arclight Server

### ISSUE THREAD

**Issue by Talan67** [Hipposgrumm/corrosive-sculk#1]
Server crashes on startup, when trying to load the mod.

[latest.log](https://github.com/Hipposgrumm/corrosive-sculk/files/12242195/latest.log)

**Comment by Hipposgrumm** [comment]
Arclight is a hybrid-type server, and therefore is bound to run into issues.
Secondly, it seems that the crash isn’t even related to Corrosive Sculk.

**Comment by Hipposgrumm** [comment]
Turns out this wasn’t an arclight problem, it was a me issue. This issue is not being tracked in #2.
