### ISSUE TITLE
Crash on Server Start Up

### ISSUE THREAD

**Issue by Talan67** [Hipposgrumm/corrosive-sculk#2]
Tested on Forge Version 47.1.1

[latest.log](https://github.com/Hipposgrumm/corrosive-sculk/files/12267772/latest.log)

**Comment by Hipposgrumm** [comment]
Oh shoot, maybe I _did_ screw something up there. _I really need to test my stuff better._

**Comment by Hipposgrumm** [comment]
Fixed, will release patch.
